name: Hello CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Say Hello
      run: |
        echo "Hello, CI World!"
        echo "Current time is $(date)"
        echo "Repository: ${{ github.repository }}"
    
    - name: Run our test script
      run: node test.js